adk_agent:
  project_id: ${GOOGLE_ADK_PROJECT_ID}
  client_secret: ${GOOGLE_ADK_CLIENT_SECRET}
  workflow_default: "default_adk_workflow"
  api_endpoint: "https://adk.googleapis.com/v1"
  timeout_seconds: 60
